
package service.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TaxCalculatorService", targetNamespace = "http://service/", wsdlLocation = "http://localhost:9090/webservice2_war/tax?wsdl")
public class TaxCalculatorService
    extends Service
{

    private final static URL TAXCALCULATORSERVICE_WSDL_LOCATION;
    private final static WebServiceException TAXCALCULATORSERVICE_EXCEPTION;
    private final static QName TAXCALCULATORSERVICE_QNAME = new QName("http://service/", "TaxCalculatorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9090/webservice2_war/tax?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TAXCALCULATORSERVICE_WSDL_LOCATION = url;
        TAXCALCULATORSERVICE_EXCEPTION = e;
    }

    public TaxCalculatorService() {
        super(__getWsdlLocation(), TAXCALCULATORSERVICE_QNAME);
    }

    public TaxCalculatorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TAXCALCULATORSERVICE_QNAME, features);
    }

    public TaxCalculatorService(URL wsdlLocation) {
        super(wsdlLocation, TAXCALCULATORSERVICE_QNAME);
    }

    public TaxCalculatorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TAXCALCULATORSERVICE_QNAME, features);
    }

    public TaxCalculatorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TaxCalculatorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TaxCalculator
     */
    @WebEndpoint(name = "TaxCalculatorPort")
    public TaxCalculator getTaxCalculatorPort() {
        return super.getPort(new QName("http://service/", "TaxCalculatorPort"), TaxCalculator.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TaxCalculator
     */
    @WebEndpoint(name = "TaxCalculatorPort")
    public TaxCalculator getTaxCalculatorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "TaxCalculatorPort"), TaxCalculator.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TAXCALCULATORSERVICE_EXCEPTION!= null) {
            throw TAXCALCULATORSERVICE_EXCEPTION;
        }
        return TAXCALCULATORSERVICE_WSDL_LOCATION;
    }

}
