
package service.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TaxCalculator", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TaxCalculator {


    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calculatePersonalIncomeTax", targetNamespace = "http://service/", className = "service.client.CalculatePersonalIncomeTax")
    @ResponseWrapper(localName = "calculatePersonalIncomeTaxResponse", targetNamespace = "http://service/", className = "service.client.CalculatePersonalIncomeTaxResponse")
    @Action(input = "http://service/TaxCalculator/calculatePersonalIncomeTaxRequest", output = "http://service/TaxCalculator/calculatePersonalIncomeTaxResponse")
    public double calculatePersonalIncomeTax(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

}
